# Projeto
sonar.projectKey=mayconaraujosantos_financesgold-api
sonar.projectName=mayconaraujosantos
sonar.projectVersion=1.0

# Organização (necessária no SonarCloud)
sonar.organization=mayconaraujosantos

# Diretório base do código
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Configuração do host (SonarCloud ou SonarQube)
sonar.host.url=https://sonarcloud.io

# Token de autenticação
sonar.login=${SONAR_TOKEN}
